import type {
  CeoCommandCenterData,
  OnboardingCommandCenterData,
} from "@/types/ceo-command-center";

export const CEO_DEMO_USER = {
  name: "Tim",
  avatarInitials: "TM",
};

export function getCeoCommandCenterMockData(): CeoCommandCenterData {
  return {
    user: CEO_DEMO_USER,
    progressSteps: [
      { id: 1, label: "Business Profile", status: "completed" },
      { id: 2, label: "Offer & Goals", status: "completed" },
      { id: 3, label: "Landing Pages", status: "completed" },
      { id: 4, label: "Pipeline & Workflow", status: "completed" },
      { id: 5, label: "Connect Accounts", status: "completed" },
      { id: 6, label: "AI Agents", status: "active" },
      { id: 7, label: "Ads Agent", status: "pending" },
      { id: 8, label: "Tracking", status: "pending" },
      { id: 9, label: "Review", status: "review" },
      { id: 10, label: "Launch", status: "pending" },
    ],
    kpis: [
      {
        id: "revenue",
        label: "Revenue This Month",
        value: "$18,400",
        trend: { value: "$18,400", change: "+28% vs last month", changePositive: true, sparkline: [12, 14, 13, 16, 15, 18, 17, 19, 18, 20] },
        icon: "dollar",
        accent: "green",
      },
      {
        id: "leads",
        label: "Leads This Month",
        value: "147",
        trend: { value: "147", change: "+35% vs last month", changePositive: true, sparkline: [8, 10, 12, 11, 14, 13, 15, 16, 14, 17] },
        icon: "users",
        accent: "blue",
      },
      {
        id: "appointments",
        label: "Appointments",
        value: "39",
        trend: { value: "39", change: "+21% vs last month", changePositive: true, sparkline: [3, 4, 3, 5, 4, 6, 5, 4, 5, 6] },
        icon: "calendar",
        accent: "purple",
      },
      {
        id: "sales",
        label: "Sales",
        value: "11",
        trend: { value: "11", change: "+22% vs last month", changePositive: true, sparkline: [1, 2, 1, 2, 2, 1, 2, 3, 2, 2] },
        icon: "cart",
        accent: "orange",
      },
      {
        id: "ad_spend",
        label: "Ad Spend",
        value: "$2,100",
        trend: { value: "$2,100", change: "-8% vs last month", changePositive: false, sparkline: [22, 21, 20, 19, 21, 20, 18, 19, 17, 18] },
        icon: "megaphone",
        accent: "pink",
      },
    ],
    healthScore: {
      score: 84,
      maxScore: 100,
      changePercent: 12,
      message: "Great! You're doing excellent.",
      breakdown: [
        { label: "Lead Generation", score: 95 },
        { label: "Follow Up", score: 67 },
        { label: "Website", score: 88 },
        { label: "Ads", score: 80 },
        { label: "Reviews", score: 58 },
        { label: "Automation", score: 90 },
      ],
    },
    revenueGoal: {
      monthlyGoal: 50000,
      currentRevenue: 18400,
      revenueGap: 31600,
      progressPercent: 37,
      leadsNeeded: 105,
      appointmentsNeeded: 37,
      salesNeeded: 14,
    },
    aiCoach: {
      greeting: "Good morning Tim! 👋",
      summary: "You're 37% toward your monthly revenue goal.\nFocus on these high-impact actions today.",
      topPriority: {
        title: "Call these 8 hot leads",
        potentialRevenue: "$12,400",
        ctaLabel: "View Leads",
        ctaHref: "/dashboard/leads",
      },
      recommendations: [
        { id: "1", text: "Launch Offer Campaign #4 — Get more leads this week" },
        { id: "2", text: "Increase Google Ads Budget — Recommended: +$20/day" },
        { id: "3", text: "Respond to 5 New Reviews — Protect and improve your reputation" },
      ],
    },
    pipeline: [
      { id: "new", label: "New Leads", count: 35, value: 7000 },
      { id: "contacted", label: "Contacted", count: 24, value: 4800 },
      { id: "qualified", label: "Qualified", count: 18, value: 6200 },
      { id: "appt", label: "Appt Set", count: 14, value: 8400 },
      { id: "estimate", label: "Estimate Sent", count: 9, value: 9500 },
      { id: "won", label: "Won", count: 5, value: 18400 },
      { id: "lost", label: "Lost", count: 2, value: 1200 },
    ],
    leadSources: [
      { id: "google", label: "Google Ads", count: 42, percent: 29, color: "#6366f1" },
      { id: "facebook", label: "Facebook Ads", count: 31, percent: 21, color: "#3b82f6" },
      { id: "organic", label: "Organic Search", count: 26, percent: 18, color: "#22d3ee" },
      { id: "referrals", label: "Referrals", count: 18, percent: 12, color: "#a855f7" },
      { id: "direct", label: "Direct", count: 30, percent: 20, color: "#f97316" },
    ],
    aiEmployees: [
      { id: "1", name: "Appointment Setter", status: "active", description: "Handling new leads & booking" },
      { id: "2", name: "Follow-Up Specialist", status: "active", description: "Following up with leads" },
      { id: "3", name: "Review Agent", status: "active", description: "Managing review requests" },
      { id: "4", name: "Missed Call Agent", status: "active", description: "Responds to missed calls" },
      { id: "5", name: "Reactivation Agent", status: "active", description: "Win back inactive customers" },
    ],
    recentActivity: [
      { id: "1", text: "New lead from Google Ads", timeAgo: "2 min ago" },
      { id: "2", text: "AI Appointment booked", timeAgo: "15 min ago" },
      { id: "3", text: "New review received ⭐⭐⭐⭐⭐", timeAgo: "1 hour ago" },
      { id: "4", text: "Payment received $1,250", timeAgo: "2 hours ago" },
      { id: "5", text: "New lead from Facebook", timeAgo: "3 hours ago" },
    ],
    tasks: [
      { id: "1", title: "Call 8 hot leads", priority: "high" },
      { id: "2", title: "Follow up on 5 estimates", priority: "high" },
      { id: "3", title: "Respond to 3 reviews", priority: "medium" },
      { id: "4", title: "Update Google Business Post", priority: "low" },
      { id: "5", title: "Check ad performance", priority: "low" },
    ],
    connectedAccounts: [
      { id: "google_ads", name: "Google Ads", status: "connected" },
      { id: "facebook", name: "Facebook", status: "connected" },
      { id: "instagram", name: "Instagram", status: "connected" },
      { id: "google_business", name: "Google Bus.", status: "connected" },
      { id: "zernio", name: "Zernio", status: "connected" },
      { id: "whatsapp", name: "WhatsApp", status: "connected" },
    ],
  };
}

export function getOnboardingCommandCenterMockData(): OnboardingCommandCenterData {
  return {
    steps: [
      { id: "business_profile", number: 1, label: "Business Profile" },
      { id: "offer_goals", number: 2, label: "Offer & Goals" },
      { id: "landing_pages", number: 3, label: "Landing Pages" },
      { id: "pipeline_workflow", number: 4, label: "Pipeline & Workflow" },
      { id: "connect_accounts", number: 5, label: "Connect Accounts" },
      { id: "ai_agents", number: 6, label: "AI Agents" },
      { id: "ads_agent", number: 7, label: "Ads Agent" },
      { id: "tracking", number: 8, label: "Tracking" },
      { id: "review", number: 9, label: "Review" },
      { id: "launch", number: 10, label: "Launch" },
    ],
    currentStepId: "business_profile",
    businessProfile: {
      businessName: "",
      industry: "",
      services: "",
      address: "",
      phone: "",
      email: "",
      website: "",
      businessHours: "",
      targetCustomer: "",
      keywords: "",
      seoMetaTitle: "",
      seoMetaDescription: "",
    mainOffer: "",
    businessDescription: "",
  },
    landingPages: [
      {
        id: "lead_gen",
        title: "Lead Generation Page",
        description: "Capture leads with a compelling offer and fast form.",
        type: "lead_gen",
      },
      {
        id: "booking",
        title: "Booking / Appointment Page",
        description: "Let prospects schedule inspections directly.",
        type: "booking",
      },
      {
        id: "special_offer",
        title: "Special Offer Page",
        description: "Promote limited-time discounts and urgency.",
        type: "special_offer",
      },
    ],
    integrations: [
      { id: "google_business", name: "Google Business Profile", connected: false },
      { id: "google_ads", name: "Google Ads", connected: false },
      { id: "meta_ads", name: "Meta Ads", connected: false },
      { id: "facebook", name: "Facebook", connected: false },
      { id: "instagram", name: "Instagram", connected: false },
      { id: "tiktok", name: "TikTok", connected: false },
      { id: "linkedin", name: "LinkedIn", connected: false },
      { id: "youtube", name: "YouTube", connected: false },
      { id: "whatsapp", name: "WhatsApp", connected: false },
      { id: "gmail", name: "Gmail", connected: false },
      { id: "stripe", name: "Stripe", connected: false },
      { id: "zapier", name: "Zapier", connected: false },
      {
        id: "zernio",
        name: "Zernio",
        description:
          "Connect Zernio to manage social posting, scheduling, inbox, analytics, comments, and multiple social accounts from one connection.",
        connected: false,
      },
    ],
    reviewChecklist: [
      { id: "profile", label: "Business Profile Complete", complete: true },
      { id: "offer", label: "Offer & Goals Complete", complete: true },
      { id: "landing", label: "Landing Page Selected", complete: true },
      { id: "pipeline", label: "Pipeline Created", complete: true },
      { id: "workflow", label: "Workflow Created", complete: true },
      { id: "accounts", label: "Accounts Connected", complete: false },
      { id: "agents", label: "AI Agents Activated", complete: false },
      { id: "ads", label: "Ads Ready", complete: false },
      { id: "tracking", label: "Tracking Ready", complete: false },
    ],
  };
}
